pipeline {
    agent any

    stages {
        stage('Secrets Demo') {
            steps {
                withCredentials([string(credentialsId: 'github-token', variable: 'TOKEN')]) {
                    sh 'echo "Token is hidden: $TOKEN"'
                }
            }
        }
    }
}
